version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "test-mongo"
    environment:
      - MONGO_DATA_DIR=${DB_DATA_DIR}
      - MONGO_LOG_DIR=${DB_LOG_DIR}
      - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - ./data/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    command: mongod
